baseURL = 'https://ceilidh-band.github.io/'
languageCode = 'en-us'
paginate = 6
theme= "hugo-cohub"
title = 'coHub'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "About Us"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "Media"
  url= "#gallery"
  weight = 2
  [[menu.Main]]
  name = "Testimonials"
  url= "#testimonials"
  weight = 3
  [[menu.Main]]
  name = "Meet the Band"
  url= "#meettheband"
  weight = 4
  [[menu.Main]]
  name = "News"
  url= "#news"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu - Currently not in use, good to add menu to footer
  #[[menu.sitemap]]
  #name = "Privacy Policy"
  #url = "/privacy/"
  #weight = 1
  #[[menu.sitemap]]
  #name = "Terms"
  #url = "/terms/"
  #weight = 2

[params]

  # Google forms options
  googleFormsURL = "https://docs.google.com/forms/d/e/1FAIpQLSeyXs0jWOmlAO5MRuHxBSw31hzKRO8FZK6cUofM9Iwi8ozusA/formResponse"
  nameID = "entry.2005620554"
  emailID = "entry.1045781291"
  subjectID = "entry.1163880769"
  messageID = "entry.839337160"

  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Some Ceilidh Band"
  formspreeURL = "https://formspree.io/mbjwlead"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/bandlogo2.png"
  footerlogo = "images/bandlogo2.png"
  footerDescription = ""

  [params.address]
  address = ""
  email = "hello@example.com"
  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  openingHours = "We are open from 7am — 7pm week days."
  phone = "+(448) 833 5272 332"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 3
  
  
